version: 1.0.0.{build}
configuration:
  - Debug
  - Release
clone_depth: 10
environment:
  matrix:
    - VS_VERSION: 12
      CMAKE_GENERATOR: Visual Studio 12 2013
      PlatformToolset: v120_xp
    - VS_VERSION: 14
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      PlatformToolset: v140_xp
before_build:
  - git submodule update --init --recursive
build_script:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/build.ps1


deploy:
    - provider: GitHub
      auth_token:
          secure: 3kV4efHXwRnfXzmJPRAOs8D7+MhwXUXYeayI/P5y114L09kJa6b6L70beXdW7yYr
      on:
          ReleaseBuild: true        # deploy on release push only

    - provider: BinTray
      username: sirknightly
      api_key:
          secure: pYWqfiZhIWvFYdjVWPXNaHobmnkXIWa4+LwoiyMTEiu4Z0CiCAW0ZrMfTKVkORKz
      subject: scp-fs2open
      repo: FSO
      package: nightly
      version: $(VersionName)
      publish: true
      override: true
      on:
          NightlyBuild: true        # deploy on nightly push only